# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ff4fb0ea-15f0-401e-bd56-e771bfbeaaa8";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5785-923A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/biggidrive" = {
    device = "/dev/disk/by-uuid/dbbf1ce5-ab00-4312-941c-8cff767e5e1d";
    fsType = "ext4";
    options = ["nofail" "x-systemd.device-timeout=10" "noatime" "defaults"];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f0871a4c-5c18-464d-a995-2bec6c7ef50d"; }
    ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
