# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel" "wl"];
  boot.extraModulePackages = [config.boot.kernelPackages.broadcom_sta];
  boot.kernelParams = [
    "intel_idle.max_cstate=1"
    "processor.max_state=1"
    "intel_pstate=disable"
    "pcie_aspm=off"
    "acpi_osi=Linux"
    "acpi_backlight=vendor"
    "libata.force=noncq"
    "libata.noacpi=1"
    "ahci.mobile_lpm_policy=1"
  ];

  # Optimize I/O for Apple SSD
  boot.kernel.sysctl = {
    "vm.dirty_ratio" = 15;
    "vm.dirty_background_ratio" = 5;
  };

  powerManagement.enable = true;
  powerManagement.cpuFreqGovernor = "schedutil";
  services.mbpfan = {
    enable = true;
    aggressive = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2a7ee3c7-badc-45fc-b118-3085efff2a69";
    fsType = "ext4";
    options = ["noatime" "discard"];  # Reduce wear, enable TRIM
  };

  boot.initrd.luks.devices."nixosroot".device = "/dev/disk/by-uuid/7d8e632d-5b71-4983-bced-7c771f5e5c12";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/67E3-17ED";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022" "noatime" "discard"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/144f9572-e967-4e0b-8443-92c9232c0cdf";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  # networking.useDHCP = lib.mkDefault true;
  networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  networking.wireless.enable = false;
  networking.wireless.iwd.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
